### PR TITLE
yoliang/code refactoring

### PR DESCRIPTION
**Pull request by chrisliang12**
1. changed home.js. added jsdoc type for the comment
2. changed index.js. changed some div to other types of tag

### CODE REVIEW

**Comment by chrisliang12** [comment]
already merged Rena's branch.

**Review by benjxia — APPROVED** [review]

**Review by xil111 — APPROVED** [review]

**Review by benjxia — COMMENTED** [review]
im adding some comments and going to try to add some unit tests, dont merge yet pls

**Comment by chrisliang12** [comment]
No problem.

**Comment by benjxia** [comment]
need to add more unit tests later, i ran out of time

**Comment by chrisliang12** [comment]
I changed some id names in the newProfileModal because I wrongly used camel case in those id names before.

**Comment by chrisliang12** [comment]
also added a form to the newProfileModal and added the required input for creating a new profile (title, expDate). These are just simple updates so I did not create a new branch for them.

**Comment by chrisliang12** [comment]
I will merge this pull request after today's meeting.

**Review by karthikv6 — APPROVED** [review]

**Pull request merged**
