### PR TITLE
Modify-product

### PR DESCRIPTION
**Pull request by benjxia**
do not merge yet, still need notifications on cancel w/ unsaved changes

### CODE REVIEW

**Comment by benjxia** [comment]
maybe ready for merge, pls review

**Review by chrisliang12 — CHANGES_REQUESTED** [review]
1. Still have bugs when users don't do any changes and want to close the modal.
2. No mode changing for editing the profile.

**Comment by benjxia** [comment]
also change profiles to go by id instead of name so we can close #28

**Comment by benjxia** [comment]
mode switching is all thats left

**Review by karthikv6 — APPROVED** [review]

**Comment by benjxia** [comment]
mode switching to be done in v2, can merge after yong fixes confirm cancel bug for unsaved changes and clicking backdrop

**Review by chrisliang12 — APPROVED** [review]

**Comment by chrisliang12** [comment]
I think modify feature is good now. Maybe others can double-check to see if there are any hidden bugs.

**Review by karthikv6 — APPROVED** [review]

**Pull request merged**
