### PR TITLE
Delete button confirmation and functionality

### PR DESCRIPTION
**Pull request by Anishkulkarni9001**

### CODE REVIEW

**Comment by chrisliang12** [comment]
I have made some changes on this branch, you can approve this pr but don't merge it to main for now.

**Review by benjxia — APPROVED** [review]
looks good but should we use another id field or just the name as unique idenitifers for profiles

**Comment by chrisliang12** [comment]
> looks good but should we use another id field or just the name as unique idenitifers for profiles

We should discuss this later in the group meeting.

**Review by chrisliang12 — APPROVED** [review]

**Comment by chrisliang12** [comment]
center the modal for deletion confirmation, and set the backdrop to static.

**Pull request merged**
