### PR TITLE
Parse tags unit test

### PR DESCRIPTION
**Pull request by Sirajpal**

### CODE REVIEW

**Review by siasheth — APPROVED** [review]

**Comment by Sirajpal** [comment]
** DONT APPROVE Yet*** adding some other tag unit tests

**Comment by Sirajpal** [comment]
Does anyone know why the unit_test ci is failing?

**Comment by benjxia** [comment]
CI pipeline will fail without localhost, don't worry about it.

**Comment by benjxia** [comment]
I updated the pipeline on another branch to ignore e2e tests.

**Review by karthikv6 — APPROVED** [review]

**Pull request merged**
