### PR TITLE
update open-page test using puppeteer

### PR DESCRIPTION
**Pull request by renawuq**

### CODE REVIEW

**Comment by renawuq** [comment]
any idea about about why does the unit_test and generate_docs did not pass

**Comment by benjxia** [comment]
not sure why gen docs didnt pass but the unit tests fail because puppeteer normally runs on localhost which isnt available when github actions tries to run it

**Review by benjxia — APPROVED** [review]
looks good. your localhost seems to run on port 5501, which could cause some issues since other people's tests run on port 5500

**Comment by benjxia** [comment]
we can fix the ports later so i just approve for now

**Comment by renawuq** [comment]
I just fix the gene doc issue, I did not update my branch before. Could you approve the other pull request?

**Pull request closed without merging**
