### PR TITLE
fix info modal bugs

### PR DESCRIPTION
**Pull request by chrisliang12**
Fix the bugs

### CODE REVIEW

**Comment by chrisliang12** [comment]
can anyone check if lines 51-57 in setup.js are indeed not needed anymore? For now, I just comment out those lines.

**Comment by kjgr** [comment]
I checked the new branch the modify functionality does not change. Lines 74-77 handle all the changing data during modifying.

**Comment by benjxia** [comment]
codeclimate is down, dont worry about it not "passing"

**Review by benjxia — APPROVED** [review]
looks like modify still works the same for me

**Review by karthikv6 — APPROVED** [review]

**Pull request merged**
