### PR TITLE
yoliang/styling

### PR DESCRIPTION
**Pull request by chrisliang12**
1. Add the team logo to the navbar
2. Update the style for the navbar (does not look good now, and needs further discussion)
3. add CSS animation to the card component
4. fix margin bugs for tag buttons
5. change the plus icon in the profile creation button
6. change the font family to Lato

### CODE REVIEW

**Comment by chrisliang12** [comment]
Does anyone know why the ci tests fail?

**Comment by chrisliang12** [comment]
Applied color scheme to more components.

**Review by benjxia — CHANGES_REQUESTED** [review]
activate css linter

**Comment by benjxia** [comment]
save/modify buttons on add profile/profile info modal look like they're disabled. Should we change them to a bolder color?

**Comment by karthikv6** [comment]
Should we change the save/modify button to a more saturated color. The current color looks like it has been grayed out and is not ready to be clicked on yet. 
image

**Comment by chrisliang12** [comment]
The button color issue has been fixed. Please merge this branch before merging other test branches to the main. The card component has been modified to show title, exp date and serial_num.

**Comment by benjxia** [comment]
is it possible to also show the note while preventing overflow?

**Review by benjxia — APPROVED** [review]

**Comment by chrisliang12** [comment]
> is it possible to also show the note while preventing overflow?

Let me see if I can quickly fix that.

**Comment by benjxia** [comment]
ill make another branch to update the pipeline since it doesnt look like e2e branch will be merged anytime soon

**Review by xiaoxi-yiren — APPROVED** [review]

**Comment by chrisliang12** [comment]
1. add notes to the card.
2. enable the scrollable feature for the modal

**Comment by chrisliang12** [comment]
If no problems, I will merge this pr.

**Comment by benjxia** [comment]
can probably shrink the max length by 20, it overflows when the window  width is decreased

**Comment by chrisliang12** [comment]
> can probably shrink the max length by 20, it overflows when the window width is decreased

you mean the notes?

**Comment by chrisliang12** [comment]
it will be really easy if we just show one line of the notes.

**Comment by chrisliang12** [comment]
> can probably shrink the max length by 20, it overflows when the window width is decreased

It's fixed now.

**Comment by benjxia** [comment]
i think it's merge ready

**Comment by chrisliang12** [comment]
> i think it's merge ready

Great

**Pull request merged**
